export enum DocumentTypeEnum {
  IdentityDocuments = 1,
  Building = 2,
  Facilities = 3,
  ActivityLicense = 4,
  Well = 5,
  OwenerShip = 6,
  EducationalDocuments_PhdPlus = 12,
  EducationalDocuments_Phd = 13,
  EducationalDocuments_Master = 14,
  EducationalDocuments_Bachelor = 15,
  EducationalDocuments_CertificatePlus = 16,
  EducationalDocuments_Certificate = 17,
  EducationalDocuments_MiddleSchoolDegree = 18,
  Certificate1 = 19,
  Certificate2 = 20,
  LackOfbackgroundDocuments = 21,
  NoAddictionDocuments = 22,
  HaveEndCArd = 24,
  HaveExemptionCard = 25,
  Official = 26,
}
