import { ListActions } from "./ListActions";

export const columns = [
  {
    Header: "شناسه",
    width: 60,
    accessor: "id",
    disableFilters: true,
  },
  {
    Header: "وضعیت اشتغال",
    accessor: "employmentStatusTitle",
    width: 250,
    disableFilters: true,
  },
  // {
  //   Header: "سازمان محل کار",
  //   accessor: "workplaceOrganizationTitle",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "نام سازمان",
  //   accessor: "organizationName",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "مدت سابقه کار",
  //   accessor: "workExperienceTitle",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "سمت در سازمان",
  //   accessor: "workPositionTitle",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "گواهی مهارت",
  //   accessor: "skillCertificateTitle",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "رشته مهارتی",
  //   accessor: "skillsField",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "تقدیرنامه",
  //   accessor: "appreciationTitle",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "گواهی مهارت از سازمان محل خدمت",
  //   accessor: "skillCertificateFromORGTitle",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "نوع بیمه",
  //   accessor: "insuranceTypeTitle",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "وضعیت بیمه تکمیلی",
  //   accessor: "perfectedInsuranceTitle",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "نوع بیمه تکمیلی",
  //   accessor: "perfectedInsuranceType",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "سابقه بیمه",
  //   accessor: "insuranceDurationTitle",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "موقعیت",
  //   accessor: "locationTitle",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "کدپستی محل کار",
  //   accessor: "workPostalCode",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "ایمیل کاری",
  //   accessor: "workEmail",
  //   width: 250,
  //   disableFilters: true,
  // },
  // {
  //   Header: "تلفن محل کار",
  //   accessor: "workPhone",
  //   width: 250,
  //   disableFilters: true,
  // },
  {
    Header: "عملیات",
    accessor: "operations",
    disableFilters: true,
    width: 150,
    Cell: ListActions,
    getProps: (props: any) => ({
      mutation: props.mutation,
      setShowEditModal: props.setShowEditModal,
      setSelectedUser: props.setSelectedUser,
      setTableData: props.setTableData,
      setInitialValues: props.setInitialValues,
      setEditRowID: props.setEditRowID,
      setIsInEditMode: props.setIsInEditMode,
      isExpert: props.isExpert,
    }),
  },
];
